### ISSUE TITLE
GetSuggestedCategories

### ISSUE THREAD

**Issue by tpharaoh** [davidtsadler/ebay-sdk-examples#16]
This is not a bug, but for some reason I am having a lot of trouble figuring out:
GetSuggestedCategoriesRequestType

Here is what I have tried:
`$catreq = new Types\GetSuggestedCategoriesRequestType(['Query'=>['electronics']]);
//$catreq->Query=['electronics'];

$catreq->RequesterCredentials = new Types\CustomSecurityHeaderType();
$catreq->RequesterCredentials->eBayAuthToken = $config['sandbox']['userToken'];

$cat= $service->getSuggestedCategories($catreq);
`

It seems query is passed in constructor of the Type... and I tried many formats for it. In the above format no matter what I write it always returns 0 categories, but no error.

**Comment by davidtsadler** [comment]
The [Query](http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/GetSuggestedCategories.html#Request.Query) field is a string so you don't need to assign an array to the property. If you want to specify multiple keywords you just separate them with a space. For example,

```
$catreq = new Types\GetSuggestedCategoriesRequestType(['Query'=>'electronics']);
// Or
$catreq->Query = 'electronics';
```

```
$catreq = new Types\GetSuggestedCategoriesRequestType(['Query'=>'electronics phones computers']);
// Or
$catreq->Query = 'electronics phones computers';
```

I also think the issue is with the sandbox. The same query on production returns some suggested categories.
