### ISSUE TITLE
Code-Formating

### ISSUE THREAD

**Issue by JProof** [davidtsadler/ebay-sdk-examples#20]
Hi David,

do you have an code-style definition-file for phpstorm?

**Comment by davidtsadler** [comment]
I don't use phpstorm so I don't have a code-style definition to hand. The SDK and examples should conform to the style outlined in [PSR-2](http://www.php-fig.org/psr/psr-2/). The SDK installs [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) as part of the developer dependencies so that you can run the command `make phpcs` to get a report of which files don't conform.
