### ISSUE TITLE
request for SetShipmentTrackingInfo example

### ISSUE THREAD

**Issue by cornernote** [davidtsadler/ebay-sdk-examples#5]
Would you please be able to provide an example of this call:
http://developer.ebay.com/devzone/merchant-data/CallRef/SetShipmentTrackingInfo.html

I cannot find a SetShipmentTrackingInfoRequestType class.

**Comment by coresmart** [comment]
Hi @davidtsadler,

I just wanted to follow up on this post.  First off great job with the SDK integration.  

Have you had a chance to complete the SetShipmentTracking functionality and if so do you have an example?

Thanks!

**Comment by davidtsadler** [comment]
At the moment the merchant data SDK is [scheduled for an April release](https://trello.com/c/L2KGdgQF/2-release-merchant-data-sdk). If you give me a few days though I may be able to create an alpha-release as a Phar or Zip that you may be able to use until the official release.

**Comment by coresmart** [comment]
David,

No worries.  I just looked more and realized I needed the trading complete sale/shipment tracking functionality instead.

Great work.

Thanks!

Paul

**Comment by cornernote** [comment]
Hi David,

Would you be able to make a pre-release as a branch? That way I can pull it with composer.

I'd be happy to use whatever you have for the moment, even if not fully ready.  I'm only running this in development at the moment so can't break anything.

**Comment by davidtsadler** [comment]
There should have been a release at the start of April but I've been busy with a few other things. I'll  can look at getting a release done for next week.

**Comment by coresmart** [comment]
Derek 

I'm all set... Sorry thought I emailed you before.  Ended using trading complete sale.

Thanks!

Paul

**Comment by davidtsadler** [comment]
No problem. I still plan to release this SDK as it's been on my TODO list for a while :)

**Comment by coresmart** [comment]
Ok great... Good luck!

**Comment by cornernote** [comment]
> There should have been a release at the start of April but I've been busy with a few other things. I'll can look at getting a release done for next week.

Awesome, thanks!

**Comment by cornernote** [comment]
Hey @davidtsadler,

Are you able to put the changes into a branch that I can play with before the release is done?

**Comment by cornernote** [comment]
Hi David,

Thanks for the example.  I would prefer to use it without sending it as a batch.  Is that possible?

Eg:

```php
        $request = new MerchantData\Types\SetShipmentTrackingInfoRequestType();
        $request->OrderID = '123457890';
        $request->IsPaid = true;
        $request->IsShipped = true;
        $request->Shipment = new MerchantData\Types\ShipmentType();
        $request->Shipment->ShipmentLineItem = new MerchantData\Types\ShipmentLineItemType();
        $request->Shipment->ShipmentLineItem->LineItem[] = new MerchantData\Types\LineItemType(array(
            'ItemID' => '123457890',
            'Quantity' => 1
        ));
        $response = $ebayUserManager->merchantDataService->setShipmentTrackingInfo($request);
```

When I try, it throws this:

```
xml_parse() expects parameter 2 to be string, object given in /vendor/dts/ebay-sdk/src/DTS/eBaySDK/Parser/XmlParser.php(67)
```

**Comment by davidtsadler** [comment]
>  I would prefer to use it without sending it as a batch. 

I'm not sure what you mean by that. Can you elaborate? With regards to the error,

```
xml_parse() expects parameter 2 to be string, object given in /vendor/dts/ebay-sdk/src/DTS/eBaySDK/Parser/XmlParser.php(67)
```

I think it is been caused by this line

```
response = $ebayUserManager->merchantDataService->setShipmentTrackingInfo($request);
```

The method [setShipmentTrackingInfo](https://github.com/davidtsadler/ebay-sdk-merchant-data/blob/master/src/DTS/eBaySDK/MerchantData/Services/MerchantDataService.php#L162) does not send the request to eBay. The LMS is different to other API's provided by eBay. There is no Merchant Data Service, unlike say the Trading service. Operations done via the LMS are performed by [uploading a file to eBay](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/large-merchant-services/04-set-shipment-tracking-info.php#L168) and then waiting for them to process it. Since this processing can take some time the LMS provides a way for users to [poll it to determine when it is completed](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/large-merchant-services/04-set-shipment-tracking-info.php#L224). At this point you have to [download another file](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/large-merchant-services/04-set-shipment-tracking-info.php#L249) to get the actual response. This response is provided as a [zip archive that contains a single XML file](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/large-merchant-services/04-set-shipment-tracking-info.php#L273).  The Merchant Data SDK is designed to take this XML response and parse it into useful PHP objects. This is done by the [setShipmentTrackingInfo](https://github.com/davidtsadler/ebay-sdk-merchant-data/blob/master/src/DTS/eBaySDK/MerchantData/Services/MerchantDataService.php#L162) method.

**Comment by cornernote** [comment]
Hi David,

What I mean is can I  setShipmentTrackingInfo and send the request to eBay without sending a file and waiting for eBay to process it?  Can I call it the same way as I call getOrders, where I give some data, and it gives a response?

**Comment by davidtsadler** [comment]
I'm afraid not. SetShipmentTrackingInfo only exists in the LMS and that API works by uploading files. The reason for this is that LMS is designed for sellers with many thousands of inventory items and processing the data can take anything from several minutes to a few hours. For example LMS can be used to launch items to eBay. It would be unreasonable to upload a AddItem request for 10,000 items and expect an instant response that contained the success or failure of every item in the request.

**Comment by davidtsadler** [comment]
According to the docs for SetShipmentTackingInfo you may be able to use [CompleteSale](http://developer.ebay.com/Devzone/XML/docs/Reference/eBay/CompleteSale.html) from the Trading API instead. This would depend on what you project requires though.

**Comment by robyerevan** [comment]
hi David

Were you able to update tracking number using LMS  SetShipmentTackingInfo ?
In my case ebay returns success response and marks item as shipped however tracking number is missing.
here is response sample

Uploading set shipment tracking info requests...Done
Request processing of set shipment tracking info...Done
Status is Scheduled
Status is Scheduled
Status is InProcess
Status is InProcess
Status is InProcess
Status is InProcess
Status is InProcess
Status is InProcess
Status is InProcess
Status is InProcess
Status is InProcess
Status is InProcess
Status is InProcess
Status is Completed
Downloading set shipment tracking info responses...Done
Unzipping /tmp/attachmenteURPIt.zip...Done
OrderLineItemID xxxxxxxxxxxx-yyyyyyyyyyyyy

**Comment by waza123x** [comment]
same shit, tracking number not added on ebay

**Comment by davidtsadler** [comment]
The LMS [Set Shipment Tracking Info](https://github.com/davidtsadler/ebay-sdk-examples/blob/master/large-merchant-services/04-set-shipment-tracking-info.php#L116
) was recently updated to match the [documentation correction announced by eBay](http://developer.ebay.com/DevZone/merchant-data/ReleaseNotes.html#959) , so hopefully the tracking number can now be set.

**Comment by amirvenus** [comment]
I am trying to reuse a job id but I am getting this error:

Error: The file has already been uploaded


Please advise
