### ISSUE TITLE
addFixedPriceItem with Free shipping method listing on ebay store issue

### ISSUE THREAD

**Issue by BillDavid07** [davidtsadler/ebay-sdk-examples#50]
Hi David,

Im having an issue regarding the addFixedPriceItem  with free shipping method on setup. after i listed the product it shows this on my product listing
- Shipping: Read item description or contact seller for details. 
- Delivery:  Varies

But before when i listed a free shipping listings it all good.

here's my code
$shippingDetails = new TTypes\ShippingDetailsType();
$shippingDetails->ShippingType = 'Flat';
$shippingService = new TTypes\ShippingServiceOptionsType();
$shippingService->ShippingServicePriority = 1;
$shippingService->ShippingService = 'ShippingMethodStandard' ;
$shippingService->ShippingServiceCost = new TTypes\AmountType(array('value' => 0.00, 'currencyID' => 'USD'));
$shippingService->ShippingServiceAdditionalCost= new TTypes\AmountType(array('value' => 0.00, 'currencyID' => 'USD'));
$shippingService->FreeShipping = true;
$shippingDetails->ShippingServiceOptions[] = $shippingService;

Please see attach file for reference
Correct listing
![listings - before](https://user-images.githubusercontent.com/26889655/31268868-c4f0685c-aab0-11e7-94a2-bc38d0ffa4d0.png)

Not Correct
![listings - after](https://user-images.githubusercontent.com/26889655/31268872-c9910038-aab0-11e7-8c06-c5f33f8e7c9a.png)

Thanks in advance,
Jerome

**Comment by davidtsadler** [comment]
Do you have the item number of the listing? One thing to check is that you haven't switched on business policies for the eBay account. If you have then the item may be using a shipping policy specified in the account rather than the one in the item.

**Comment by BillDavid07** [comment]
Hi David, Thanks for your reply. i already ix it by changing the code to addItems and now i can list item with free shipping. :)

Cheers!

**Comment by davidtsadler** [comment]
Good to hear.

**Comment by BillDavid07** [comment]
Sorry, i just want to ask a question about the excludeShipLocation why is it not showing on my ebay item listing. heres my code

$shippingDetails->ExcludeShipToLocation = array(
'Alaska/Hawaii',
'US Protectorates',
 'APO/FPO',
'PO Box'
);
$item->ShippingDetails = $shippingDetails;
$item->ShipToLocations[] = 'US';

$item->ReturnPolicy = new TTypes\ReturnPolicyType();
$item->ReturnPolicy->ReturnsAcceptedOption = 'ReturnsAccepted';
$item->ReturnPolicy->RefundOption = 'MoneyBack';
$item->ReturnPolicy->ReturnsWithinOption = 'Days_30';
$item->ReturnPolicy->ShippingCostPaidByOption = 'Buyer';
$item->ReturnPolicy->RestockingFeeValue = "15% restocking fee may apply";
$item->ReturnPolicy->RestockingFeeValueOption = Enums\RestockingFeeCodeType::C_PERCENT_15;

$container = new TTypes\AddItemRequestContainerType();
$container->MessageID = $hashids->encode($list->id);
$container->Item = $item;
$request->AddItemRequestContainer[] = $container;
$response = $service->addItems($request);

**Comment by davidtsadler** [comment]
I'm not sure at without spending a bit more time on it. One thing I always recommend is to manually create the item through eBay itself. Create the item exactly how you would like it done through the API and list it on the sandbox. Then use GetItem in the API explorer, or code, and study the XML in the response. The reason is that there is normally a one to one mapping between the fields in GetItem and those in AddItem. In the past I have studied the XML from GetItem to see how eBay specified the information and then used the same fields and values in  AddItem. For example, when I was first learning the API I would manually create a listing with a single shipping service. Then call GetItem to see what fields where set  and then re-created them in AddItem. From there I moved onto things like multi-variations. Again I created them manually and then called GetItem. Looking at the response and combining it with the eBay documentation help me a lot when I was first starting.

**Comment by BillDavid07** [comment]
Ohh i see. nice! thanks for the info. it really help me a lot. 

thanks again for your reply. will closed now the ticket. :)

**Comment by davidtsadler** [comment]
No worries.  I have a [forum](http://forum.devbay.net/) available for further questions. If you do use it let me know if there are any issues with it as I'm still learning how to set it up correctly.

**Comment by BillDavid07** [comment]
Yeah sure thing mate. i already visit your forum before. cheers! :)
